PROFILE_DIR = "data/profile"
YANEURAOU_MOVEGEN_EXE = "data/testcase/YaneuraOu-movegen.exe"
YANEURAOU_KIFU_DECODER_EXE = "data/testcase/YaneuraOu-kifu-decoder.exe"
MOVEGEN_TESTCAST_PATH = "data/testcase/generate_position_testcase.pickle"
MODEL_OUTPUT_DIR = "data/model"
BAD_MOVE_STATICS_OUTPUT_DIR = "data/bad_move_statistics"
